Add-Type -AssemblyName System.Drawing
$canvas = [System.Drawing.Bitmap]::new(1200,630)
$g = [System.Drawing.Graphics]::FromImage($canvas)
$g.SmoothingMode = 'AntiAlias'
$g.TextRenderingHint = 'AntiAliasGridFit'
$bg = [System.Drawing.Drawing2D.LinearGradientBrush]::new([System.Drawing.Rectangle]::new(0,0,1200,630),[System.Drawing.Color]::FromArgb(5,10,20),[System.Drawing.Color]::FromArgb(19,35,54),25)
$g.FillRectangle($bg,0,0,1200,630)
$rng = [Random]::new(123)
for($i=0;$i -lt 220;$i++) {
  $brush = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb($rng.Next(35,180),196,217,235))
  $size = $rng.Next(1,3)
  $g.FillEllipse($brush,$rng.Next(1200),$rng.Next(630),$size,$size)
  $brush.Dispose()
}
$planet = [System.Drawing.Drawing2D.LinearGradientBrush]::new([System.Drawing.Rectangle]::new(805,108,370,370),[System.Drawing.Color]::FromArgb(120,152,163),[System.Drawing.Color]::FromArgb(7,16,29),35)
$g.FillEllipse($planet,805,108,370,370)
$state = $g.Save()
$g.TranslateTransform(990,293)
$g.RotateTransform(-25)
for($i=0;$i -lt 16;$i++) {
  $pen = [System.Drawing.Pen]::new([System.Drawing.Color]::FromArgb(55,163,180,176),1.4)
  $g.DrawEllipse($pen,-270-$i*2,-65-$i*.8,540+$i*4,130+$i*1.6)
  $pen.Dispose()
}
$g.Restore($state)
$shade = [System.Drawing.Drawing2D.LinearGradientBrush]::new([System.Drawing.Rectangle]::new(0,0,840,630),[System.Drawing.Color]::FromArgb(245,5,10,20),[System.Drawing.Color]::FromArgb(0,5,10,20),0)
$g.FillRectangle($shade,0,0,840,630)
$white = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(238,241,234))
$muted = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(165,183,197))
$gold = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(211,184,139))
$small = [System.Drawing.Font]::new('Segoe UI',15,[System.Drawing.FontStyle]::Regular)
$title = [System.Drawing.Font]::new('Segoe UI',64,[System.Drawing.FontStyle]::Regular)
$subtitle = [System.Drawing.Font]::new('Segoe UI',25,[System.Drawing.FontStyle]::Regular)
$g.DrawString('YOUR QUIET CORNER OF THE UNIVERSE',$small,$gold,74,145)
$g.DrawString('Space Drift',$title,$white,66,192)
$g.DrawString("Space ambience for`nstudy & focus.",$subtitle,$muted,74,302)
$g.DrawString('ENDLESS JOURNEYS  /  GENTLE MUSIC  /  FREE',$small,$muted,74,518)
# Small original rocket silhouette and a soft exhaust trail.
$state = $g.Save()
$g.TranslateTransform(834,483)
$g.RotateTransform(35)
$hull = [System.Drawing.Drawing2D.GraphicsPath]::new()
$hull.AddBezier(0,-71,-19,-51,-17,10,-12,29)
$hull.AddLine(-12,29,12,29)
$hull.AddBezier(12,29,17,10,19,-51,0,-71)
$g.FillPath($white,$hull)
$window = [System.Drawing.SolidBrush]::new([System.Drawing.Color]::FromArgb(31,65,85))
$g.FillEllipse($window,-6,-38,12,18)
$g.FillPolygon($muted,[System.Drawing.Point[]]@([System.Drawing.Point]::new(-12,1),[System.Drawing.Point]::new(-28,31),[System.Drawing.Point]::new(-12,25)))
$g.FillPolygon($muted,[System.Drawing.Point[]]@([System.Drawing.Point]::new(12,1),[System.Drawing.Point]::new(28,31),[System.Drawing.Point]::new(12,25)))
$flame = [System.Drawing.Drawing2D.LinearGradientBrush]::new([System.Drawing.Rectangle]::new(-10,29,20,94),[System.Drawing.Color]::FromArgb(170,141,206,238),[System.Drawing.Color]::FromArgb(0,141,206,238),90)
$g.FillPolygon($flame,[System.Drawing.Point[]]@([System.Drawing.Point]::new(-9,29),[System.Drawing.Point]::new(9,29),[System.Drawing.Point]::new(0,123)))
$g.Restore($state)
$canvas.Save((Join-Path $PSScriptRoot '../assets/social-card.png'),[System.Drawing.Imaging.ImageFormat]::Png)
foreach($item in @($bg,$planet,$shade,$white,$muted,$gold,$small,$title,$subtitle,$hull,$window,$flame,$g,$canvas)){$item.Dispose()}
